#!/bin/bash
bash_colors_dir="${HOME}/dotfiles/bashrc.d/.promptrc.d"
bash_colors_path="$bash_colors_dir"/bash_colors.sh
mkdir -p "$bash_colors_dir"
if [ ! -f "$bash_colors_path" ]; then
    curl -o "$bash_colors_path" \
    https://raw.githubusercontent.com/mercuriev/bash_colors/master/bash_colors.sh
fi

export BLACK="$(tput setaf 0)"
export RED="$(tput setaf 1)"
export GREEN="$(tput setaf 2)"
export YELLOW="$(tput setaf 3)"
export BLUE="$(tput setaf 4)"
export MAGENTA="$(tput setaf 5)"
export CYAN="$(tput setaf 6)"
export WHITE="$(tput setaf 6)"
export RESET="$(tput sgr0)"

parse_git_branch() {
git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
# https://gist.github.com/kevinchappell/09ca3805a9531b818579
export PS1='[\A ${GREEN}\u${RESET}${CYAN}@\H${RESET} \W ${RED}$(parse_git_branch)${RESET}]\n\$ '
