#!/bin/bash
# aliases
alias bashrc='source  ~/.bashrc'
alias crontab="crontab -i"
alias less="less -R"
# git bash 環境の場合、 start でコマンドが通る
if ! command -v start &> /dev/null
then
    # ubuntu 環境の場合、 start でエクスプローラ (nautilus) が開くようにする
    alias start="nautilus"
fi