#!/bin/bash
# env
export LESSCHARSET=utf-8

# aliases
alias bashrc='source  ~/.bashrc'
alias crontab="crontab -i"
alias less="less -R"

# git bash 環境の場合、 start でコマンドが通る
if ! command -v start &> /dev/null
then
    # ubuntu 環境の場合、 start でエクスプローラ (nautilus) が開くようにする
    alias start="nautilus"
fi

# functions
trim_comment() {
    if [ -z "$1" ]; then
        echo "エラー: 引数が必要です"
        exit 1
    fi
    cat $1 | sed '/^[ \t]*#/d' | sed '/^$/d'
}

abpath () {
    relative_path=`echo $1|sed 's|^\./||g'`
    echo `pwd`'/'`ls ${relative_path}`
}

command_not_found_handle() {
    local cmd
    cmd=${1##*/}
    echo "\"${cmd}\" not found \(^o^)/"
}

docker-stop-all() {
    which docker >/dev/null
    if [ $? -ne 0 ];then
        echo '`docker` command not found'
        return 1;
    fi
    docker stop `docker ps -q`
}

docker-compose-up-force () {
    docker-stop-all
    docker-compose up
}

upload-pubkey-to () {
    PubKey=$(cat $1)
    Host=$2
    ssh ${Host} -C "mkdir -p ~/.ssh/ && echo ${PubKey} >> ~/.ssh/authorized_keys && chmod 700 ~/.ssh/ && chmod 600 ~/.ssh/authorized_keys"
}
