#!/bin/bash
# env
export LESSCHARSET=utf-8

# aliases
alias bashrc='source  ~/.bashrc'
alias crontab="crontab -i"
alias less="less -R"
alias ll='ls -l --color=auto'
alias lla='ls -la --color=auto'
alias ls='ls --color=auto'
alias l.='ls -d .* --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'

# git bash 環境の場合、 start でコマンドが通る
if ! command -v start &> /dev/null
then
    # ubuntu 環境の場合、 start でエクスプローラ (nautilus) が開くようにする
    alias start="nautilus"
fi

# functions
trim_comment() {
    if [ -z "$1" ]; then
        echo "エラー: 引数が必要です"
        exit 1
    fi
    cat $1 | sed '/^[ \t]*#/d' | sed '/^$/d'
}

abpath () {
    relative_path=`echo $1|sed 's|^\./||g'`
    echo `pwd`'/'`ls ${relative_path}`
}

command_not_found_handle() {
    local cmd
    cmd=${1##*/}
    echo "\"${cmd}\" not found \(^o^)/"
}

docker-stop-all() {
    which docker >/dev/null
    if [ $? -ne 0 ];then
        echo '`docker` command not found'
        return 1;
    fi
    docker stop `docker ps -q`
}

docker-compose-up-force () {
    docker-stop-all
    docker-compose up
}

ssh-upload-pubkey-to () {
    if [ "$1" = "" ]; then
        echo "You have to specify first arg"
        return 1
    fi
    KeyPath=$2
    if [ "$KeyPath" = "" ]; then
        KeyPath=~/.ssh/id_ed25519.pub
    fi
    PubKey=$(cat $KeyPath)
    ssh ${Host} -C "mkdir -p ~/.ssh/ && echo ${PubKey} >> ~/.ssh/authorized_keys && chmod 700 ~/.ssh/ && chmod 600 ~/.ssh/authorized_keys"
}

# root ユーザで鍵ファイルログインできるようにするスクリプト
# gcp 環境などで便利
ssh-upload-pubkey-to-root () {
    if [ "$1" = "" ]; then
        echo "You have to specify first arg"
        return
    fi
    KeyPath=~/.ssh/id_ed25519.pub
    PubKey=$(cat $KeyPath)
    ssh-upload-pubkey-to "$1"
    ssh "$1" -C "sudo su -c 'mkdir -p /root/.ssh/ && echo ${PubKey} >> /root/.ssh/authorized_keys && chmod 700 /root/.ssh/ && chmod 600 /root/.ssh/authorized_keys'"
    ssh "$1" -C "sudo sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config && sudo systemctl restart sshd"
}